apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume1 ## Lembra de mudar o nome aqui!
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
